# Generated by Django 2.1.7 on 2019-03-15 20:29

from django.db import migrations, models
import hfapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hfmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=hfapp.models.get_image_path)),
            ],
        ),
    ]
